//serinix/include/serinix/unistd.h 

#ifndef _SERINIX_UNISTD_H
#define _SERINIX_UNISTD_H 

#define SYS_exit		1
#define SYS_fork		2
#define SYS_read		3
#define SYS_write		4
#define SYS_open		5
#define SYS_close		6
#define SYS_waitpid		7
#define SYS_creat		8
#define SYS_link		9
#define SYS_unlink		10
#define SYS_execve		11
#define SYS_chdir		12
#define SYS_time		13
#define SYS_mknod		14
#define SYS_chmod		15
#define SYS_lchown		16
#define SYS_break		17		 
#define SYS_oldstat		18
#define SYS_lseek		19
#define SYS_getpid		20
#define SYS_mount		21
#define SYS_umount		22
#define SYS_setuid		23
#define SYS_getuid		24
#define SYS_stime		25
#define SYS_alarm		27
#define SYS_oldfstat		28
#define SYS_pause		29
#define SYS_utime		30
#define SYS_access		33
#define SYS_ftime		35
#define SYS_sync		36
#define SYS_kill		37
#define SYS_rename		38
#define SYS_mkdir		39
#define SYS_rmdir		40
#define SYS_dup			41
#define SYS_pipe		42
#define SYS_times		43
#define SYS_brk			45
#define SYS_setgid		46
#define SYS_getgid		47
#define SYS_signal		48
#define SYS_geteuid		49
#define SYS_getegid		50
#define SYS_umount2		52	 
#define SYS_ioctl		54
#define SYS_fcntl		55
#define SYS_setpgid		57
#define SYS_ulimit		58		 
#define SYS_olduname	59
#define SYS_umask		60
#define SYS_chroot		61
#define SYS_ustat		62
#define SYS_dup2		63
#define SYS_getppid		64
#define SYS_getpgrp		65
#define SYS_setsid		66
#define SYS_sigaction		67
#define SYS_setreuid		70
#define SYS_setregid		71
#define SYS_sigsuspend		72
#define SYS_sigpending		73
#define SYS_sethostname		74
#define SYS_setrlimit		75
#define SYS_getrlimit		76
#define SYS_getrusage		77
#define SYS_gettimeofday	78
#define SYS_settimeofday	79
#define SYS_getgroups		80
#define SYS_setgroups		81
#define SYS_symlink		83
#define SYS_readlink		85
#define SYS_reboot		88
#define SYS_munmap		91
#define SYS_truncate		92
#define SYS_ftruncate		93
#define SYS_fchmod		94
#define SYS_fchown		95
#define SYS_statfs		99
#define SYS_fstatfs		100
#define SYS_socketcall 		102
#define SYS_setitimer		104
#define SYS_getitimer		105
#define SYS_uname		109
#define SYS_iopl		110
#define SYS_wait4		114
#define SYS_sysinfo		116
#define SYS_ipc			117
#define SYS_fsync		118
#define SYS_sigreturn		119
#define SYS_setdomainname	121
#define SYS_newuname		122
#define SYS_mprotect 		125
#define SYS_sigprocmask		126
#define SYS_getpgid 		132
#define SYS_fchdir		133
#define SYS_personality		136
#define SYS_setfsuid		138
#define SYS_setfsgid		139
#define SYS_llseek		140
#define SYS_getdents		141
#define SYS_select		142
#define SYS_flock		143
#define SYS_readv		145
#define SYS_writev		146
#define SYS_getsid		147
#define SYS_fdatasync		148
#define SYS_nanosleep		162
#define SYS_chown		182
#define SYS_getcwd		183
#define SYS_vfork		190
#define SYS_mmap2		192
#define SYS_truncate64		193
#define SYS_ftruncate64		194
#define SYS_stat64		195
#define SYS_lstat64		196
#define SYS_fstat64		197
#define SYS_chown32		212
#define SYS_getdents64		220
#define SYS_fcntl64		221
#define SYS_utimes		271

#endif /* _SERINIX_UNISTD_H */
